d08/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('articles/', views.ArticleListView.as_view(), name='articles'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('publications/', views.PublicationListView.as_view(), name='publications'),
    path('article/<int:pk>/', views.ArticleDetailView.as_view(), name='detail'),
    path('favourites/', views.FavouriteListView.as_view(), name='favourites'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('publish/', views.PublishView.as_view(), name='publish'),
    path('article/<int:pk>/add-to-favourite/', views.AddToFavouriteView.as_view(), name='add_to_favourite'),
]

d08/d08/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('articles.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
)

d08/articles/models.py
from django.db import models
from django.contrib.auth.models import User

class Article(models.Model):
    title = models.CharField(max_length=64, null=False)
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=False)
    created = models.DateTimeField(auto_now_add=True, null=False)
    synopsis = models.CharField(max_length=312, null=False)
    content = models.TextField(null=False)

    def __str__(self):
        return self.title

class UserFavouriteArticle(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=False)
    article = models.ForeignKey(Article, on_delete=models.CASCADE, null=False)

    def __str__(self):
        return self.article.title

    class Meta:
        unique_together = ('user', 'article')

d08/articles/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Article

# class RegisterForm(UserCreationForm):
#     def __init__(self, *args, **kwargs):
#         super().__init__(*args, **kwargs)
#         for field in self.fields.values():
#             field.widget.attrs.update({'class': 'form-control'})

class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']

class PublishForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'synopsis', 'content']

d08/articles/views.py
from django.shortcuts import redirect
from django.views.generic import ListView, DetailView, RedirectView
from django.contrib.auth.views import LoginView as AuthLoginView, LogoutView as AuthLogoutView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Article, UserFavouriteArticle
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy
from .forms import RegisterForm, PublishForm
from django.contrib.auth.forms import AuthenticationForm

class PublishView(LoginRequiredMixin, CreateView):
    form_class = PublishForm
    template_name = 'articles/publish.html'
    success_url = reverse_lazy('articles:publications')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

class HomeView(RedirectView):
    url = '/articles/'

class ArticleListView(ListView):
    model = Article
    template_name = 'articles/article_list.html'
    ordering = ['-created']
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['login_form'] = AuthenticationForm()
        return context

class LoginView(AuthLoginView):
    template_name = 'articles/login.html'
    redirect_authenticated_user = True
    success_url = reverse_lazy('articles:articles')

class PublicationListView(LoginRequiredMixin, ListView):
    model = Article
    template_name = 'articles/publication_list.html'
    def get_queryset(self):
        return Article.objects.filter(author=self.request.user)

class ArticleDetailView(DetailView):
    model = Article
    template_name = 'articles/article_detail.html'

class LogoutView(AuthLogoutView):
    next_page = '/'

class FavouriteListView(LoginRequiredMixin, ListView):
    model = UserFavouriteArticle
    template_name = 'articles/favourite_list.html'
    def get_queryset(self):
        return UserFavouriteArticle.objects.filter(user=self.request.user)
    
class RegisterView(CreateView):
    form_class = RegisterForm
    template_name = 'articles/register.html'
    success_url = reverse_lazy('articles:login')

class RegisterView(CreateView):
    form_class = RegisterForm
    template_name = 'articles/register.html'
    success_url = reverse_lazy('articles:login')

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('articles:home')  # Redirect authenticated users
        return super().dispatch(request, *args, **kwargs)
    
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

class AddToFavouriteView(LoginRequiredMixin, CreateView):
    model = UserFavouriteArticle
    fields = []
    template_name = 'articles/add_to_favourite.html'

    def get_success_url(self):
        return reverse_lazy('articles:detail', kwargs={'pk': self.kwargs['pk']})

    def form_valid(self, form):
        # Check if the favorite already exists
        if UserFavouriteArticle.objects.filter(
            user=self.request.user,
            article=Article.objects.get(pk=self.kwargs['pk'])
        ).exists():
            # If it exists, redirect without creating a duplicate
            return self.get(self.request)
        # Otherwise, proceed with creation
        form.instance.user = self.request.user
        form.instance.article = Article.objects.get(pk=self.kwargs['pk'])
        return super().form_valid(form)
    
class LogoutView(AuthLogoutView):
    # template_name = 'articles/logout.html'
    # next_page = '/'
    next_page = reverse_lazy('articles:home')

d08/articles/templates/articles/_article_list.html
<!DOCTYPE html>
<html>
<head><title>Articles</title></head>
<body>
  <h1>Articles</h1>
  <table border="1">
    <thead>
      <tr>
        <th>Title</th>
        <th>Author</th>
        <th>Created</th>
        <th>Synopsis</th>
      </tr>
    </thead>
    <tbody>
      {% for article in object_list %}
      <tr>
        <td>{{ article.title }}</td>
        <td>{{ article.author.username }}</td>
        <td>{{ article.created }}</td>
        <td>{{ article.synopsis }}</td>
        <td><a href="{% url 'articles:detail' article.pk %}">{{ article.title }}</a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</body>
</html>

d08/articles/templates/articles/add_to_favourite.html
{% extends 'base.html' %}
{% load i18n %}
<form method="post">
    {% csrf_token %}
    <button type="submit">Add to Favourites</button>
</form>

d08/articles/templates/articles/article_detail.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}{{ object.title }}{% endblock %}
{% block content %}
  <h1>{{ object.title }}</h1>
  <p>Author: {{ object.author.username }}</p>
  <p>Created: {{ object.created }}</p>
  <p>Synopsis: {{ object.synopsis }}</p>
  <p>Content: {{ object.content }}</p>
  {% if user.is_authenticated %}
    <form method="post" action="{% url 'articles:add_to_favourite' object.pk %}">
      {% csrf_token %}
      <button type="submit">{% trans "Add to Favourites" %}</button>
    </form>
  {% endif %}
{% endblock %}

d08/articles/templates/articles/article_list.html
{% extends 'base.html' %}
{% load i18n humanize %}
{% block title %}{% trans "Articles" %}{% endblock %}
{% block content %}
  <table class="table table-striped">
    <thead>
      <tr>
        <th>{% trans "Title" %}</th>
        <th>{% trans "Synopsis" %}</th>
        <th>{% trans "Writer" %}</th>
        <th>{% trans "Created" %}</th>
        <th>{% trans "When" %}</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      {% for article in object_list %}
        <tr>
          <td>{{ article.title|truncatechars:10 }}</td>
          <td>{{ article.synopsis|truncatechars:20 }}</td>
          <td>{{ article.author.username }}</td>
          <td>{{ article.created|date:"M d, Y, H:i a" }}</td>
          <td>{{ article.created|naturaltime }}</td>
          <td>
            <a href="{% url 'articles:detail' article.pk %}" class="btn btn-primary btn-sm">{% trans "Read" %}</a>
          </td>
        </tr>
      {% empty %}
        <tr>
          <td colspan="6">{% trans "No articles available." %}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

d08/articles/templates/articles/favourite_list.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}Favourites{% endblock %}
{% block content %}
  <h1>{% trans "Your Favourites" %}</h1>
  {% if object_list %}
  <ul>
    {% for fav in object_list %}
    <li><a href="{% url 'articles:detail' fav.article.pk %}">{{ fav.article.title }}</a></li>
    {% endfor %}
  </ul>
  {% else %}
  <p>{% trans "You have no favourite articles yet." %}</p>
  {% endif %}
  <form method="post" action="{% url 'articles:logout' %}">
    {% csrf_token %}
    <button type="submit">{% trans "Logout" %}</button>
  </form>
{% endblock %}

d08/articles/templates/articles/login.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}Login{% endblock %}
{% block content %}
  <h1>Login</h1>
  {% if form.errors %}
    <p>Invalid username or password.</p>
  {% endif %}
  <form method="post" action="{% url 'articles:login' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">{% trans "Login" %}</button>
  </form>
{% endblock %}

d08/articles/templates/articles/logout.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}Logout{% endblock %}
{% block content %}
  <h1>{% trans "Logged Out" %}</h1>
  <p>{% trans "You have been successfully logged out." %}</p>
  <a href="{% url 'articles:login' %}">{% trans "Log in again" %}</a>
{% endblock %}

d08/articles/templates/articles/publication_list.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}Publications{% endblock %}
{% block content %}
  <h1>Your Publications</h1>
  <table border="1">
    <thead>
      <tr>
        <th>Title</th>
        <th>Synopsis</th>
        <th>Created</th>
      </tr>
    </thead>
    <tbody>
      <a href="{% url 'articles:publish' %}">Publish New Article</a>
      {% for article in object_list %}
      <tr>
        <td><a href="{% url 'articles:detail' article.pk %}">{{ article.title }}</a></td>
        <td>{{ article.synopsis }}</td>
        <td>{{ article.created }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  <form method="post" action="{% url 'articles:logout' %}">
    {% csrf_token %}
    <button type="submit">{% trans "Logout" %}</button>
  </form>
{% endblock %}

d08/articles/templates/articles/publish.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}Publish{% endblock %}
{% block content %}
  <h1>Publish an Article</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Publish</button>
  </form>
{% endblock %}

d08/articles/templates/articles/register.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}Register{% endblock %}
{% block content %}
  <h1>Register</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Register</button>
  </form>
{% endblock %}